name: Assign issue with IssueOps
on:
  issues:
    types: [opened]
jobs:
  assign-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' &&
      (github.event.action == 'opened') &&
      contains(github.event.issue.labels.*.name, 'assign-issue')
    permissions:
      contents: read
      issues: write

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser

    - name: create repo
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |

    - name: Post failure message
      uses: actions/github-script@v6
      with:
        script: |
          let commentBody
          commentBody = `😢 The issue body could not be parsed, @${{ github.actor }}. Please open a new issue using the issue template and ensure your formatting and line spacing remains untouched.`
          await github.rest.issues.addAssignees({
            owner: '${{ github.REPOSITORY_OWNER }}',
            repo: '${{ github.event.repository.name }}',
            issue_number: ${{ github.event.issue.number }},
            assignees: 'joshjohanning, mickeygousset'
          })
