name: Assign issue with IssueOps
on:
  issues:
    types: [opened]
jobs:
  assign-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' &&
      (github.event.action == 'opened') &&
      contains(github.event.issue.labels.*.name, 'assign-issue')
    permissions:
      contents: write
      issues: write

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser

    - name: create repo
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |

    - name: Assign Issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ADMIN_TOKEN }}
        debug: true
        script: |
          await github.rest.issues.addAssignees({
            owner: '${{ github.REPOSITORY_OWNER }}',
            repo: '${{ github.event.repository.name }}',
            issue_number: ${{ github.event.issue.number }},
            assignees: '["joshjohanning"]'
          })
